### ISSUE TITLE
how can i run test on the local

### ISSUE THREAD

**Issue by takaaptech** [cuo9958/wechat-game#1]
Hi!
Your game engine looks great and very small
How can I install and run the test on local webserver?
Thank so much!

**Comment by cuo9958** [comment]
it juest in wechat and use 'wx.createCanvas'

y can see 'https://developers.weixin.qq.com/miniprogram/dev/api/wx.createCanvasContext.html'

**Comment by takaaptech** [comment]
Hi @cuo9958 !
Thank you so much!
